
import { Category, Testimonial, Service } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'house-cleaning',
    name: 'House Cleaning',
    description: 'Deep cleaning, regular cleaning',
    serviceCount: 4,
    imageUrl: 'https://picsum.photos/400/300?random=1',
    popular: true,
  },
  {
    id: 'plumbing',
    name: 'Plumbing',
    description: 'Pipe repair, installation',
    serviceCount: 4,
    imageUrl: 'https://picsum.photos/400/300?random=2',
  },
  {
    id: 'electrical',
    name: 'Electrical',
    description: 'Wiring, switches, repairs',
    serviceCount: 4,
    imageUrl: 'https://picsum.photos/400/300?random=3',
    popular: true,
  },
  {
    id: 'ac-repair',
    name: 'AC Repair',
    description: 'Installation, maintenance',
    serviceCount: 3,
    imageUrl: 'https://picsum.photos/400/300?random=4',
  },
  {
    id: 'appliance-repair',
    name: 'Appliance Repair',
    description: 'Washing machine, refrigerator',
    serviceCount: 4,
    imageUrl: 'https://picsum.photos/400/300?random=5',
    popular: true,
  },
  {
    id: 'painting',
    name: 'Painting',
    description: 'Interior, exterior painting',
    serviceCount: 3,
    imageUrl: 'https://picsum.photos/400/300?random=6',
  },
  {
    id: 'carpentry',
    name: 'Carpentry',
    description: 'Furniture repair, installation',
    serviceCount: 3,
    imageUrl: 'https://picsum.photos/400/300?random=7',
  },
  {
    id: 'pest-control',
    name: 'Pest Control',
    description: 'Termites, cockroaches, ants',
    serviceCount: 3,
    imageUrl: 'https://picsum.photos/400/300?random=8',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    name: 'Priya Sharma',
    location: 'Mumbai',
    initials: 'P',
    rating: 5,
    service: 'House Cleaning',
    comment: 'Amazing service! The professional was punctual, courteous, and did an excellent job cleaning my home. Will definitely book again.',
  },
  
  {
    name: 'Rajesh Kumar',
    location: 'Delhi',
    avatarUrl: 'https://picsum.photos/100/100?random=9',
    initials: 'R',
    rating: 5,
    service: 'Plumbing',
    comment: 'Quick response and professional service. Fixed my plumbing issue efficiently and provided warranty on the work.',
  },
  {
    name: 'Anita Desai',
    location: 'Bangalore',
    avatarUrl: 'https://picsum.photos/100/100?random=10',
    initials: 'A',
    rating: 5,
    service: 'Electrical',
    comment: 'Excellent work! The electrician was knowledgeable and solved all my electrical problems safely.',
  },
  {
    name: 'Vikram Singh',
    location: 'Chennai',
    avatarUrl: 'https://picsum.photos/100/100?random=11',
    initials: 'V',
    rating: 5,
    service: 'AC Repair',
    comment: 'Professional service at a reasonable price. My AC is working like new again!',
  },
];

export const SERVICES: Service[] = [
  // Electrical
  {
    id: 1,
    categoryId: 'electrical',
    title: 'Electrical Wiring & Repairs',
    description: 'Safe and reliable electrical work by certified electricians',
    price: 799,
    imageUrl: 'https://picsum.photos/400/300?random=3',
    tags: ['Licensed', 'Safety Certified', 'Warranty'],
    professional: { name: 'Suresh Patel', avatarUrl: 'https://picsum.photos/100/100?random=12', experience: '10+ years experience' },
    rating: 4.9,
    reviews: 654,
    duration: '2-3 hours',
    location: 'Mumbai',
    verified: true,
  },
  {
  id: 348,
    categoryId: 'electrical',
    title: 'Electrical Fan Repairing',
    description: 'Safe and reliable electrical work by certified electricians',
    price: 299,
    imageUrl: 'https://picsum.photos/400/300?random=348',
    tags: ['Licensed', 'Safety Certified', 'Warranty'],
    professional: { name: 'santosh', avatarUrl: 'https://picsum.photos/100/100?random=126', experience: '5+ years experience' },
    rating: 4.5,
    reviews: 684,
    duration: '2-3 hours',
    location: 'bhigan',
    verified: true,
  },
  {
    id: 101,
    categoryId: 'electrical',
    title: 'Switch & Socket Installation',
    description: 'Installation and repair of switches, sockets, and switchboards.',
    price: 349,
    imageUrl: 'https://picsum.photos/400/300?random=101',
    tags: ['Quick Service', 'Safety Check'],
    professional: { name: 'Ramesh Gupta', avatarUrl: 'https://picsum.photos/100/100?random=102', experience: '7+ years experience' },
    rating: 4.8,
    reviews: 321,
    duration: '1-2 hours',
    location: 'Delhi',
    verified: true,
  },
  {
    id: 102,
    categoryId: 'electrical',
    title: 'Ceiling Fan Installation',
    description: 'Hassle-free installation of ceiling fans of all types.',
    price: 499,
    imageUrl: 'https://picsum.photos/400/300?random=103',
    tags: ['All Brands', 'Clean Work'],
    professional: { name: 'Suresh Patel', avatarUrl: 'https://picsum.photos/100/100?random=12', experience: '10+ years experience' },
    rating: 4.9,
    reviews: 512,
    duration: '1 hour',
    location: 'Mumbai',
    availableNow: true,
  },
  {
    id: 103,
    categoryId: 'electrical',
    title: 'Inverter & UPS Services',
    description: 'Installation, repair, and battery replacement for inverters.',
    price: 899,
    imageUrl: 'https://picsum.photos/400/300?random=104',
    tags: ['Battery Health Check', 'Warranty'],
    professional: { name: 'Anil Verma', avatarUrl: 'https://picsum.photos/100/100?random=105', experience: '12+ years experience' },
    rating: 4.7,
    reviews: 450,
    duration: '2-3 hours',
    location: 'Bangalore',
    verified: true,
  },

  // AC Repair
  {
    id: 2,
    categoryId: 'ac-repair',
    title: 'AC Service & Repair',
    description: 'Complete AC maintenance, repair, and installation services',
    price: 1299,
    imageUrl: 'https://picsum.photos/400/300?random=4',
    tags: ['All Brands', 'Genuine Parts', '3 Month Warranty'],
    professional: { name: 'Vikram Singh', avatarUrl: 'https://picsum.photos/100/100?random=13', experience: '6+ years experience' },
    rating: 4.6,
    reviews: 423,
    duration: '1-3 hours',
    location: 'Mumbai',
    availableNow: true,
    verified: true,
  },
   {
    id: 201,
    categoryId: 'ac-repair',
    title: 'AC Installation/Uninstallation',
    description: 'Professional installation and uninstallation for Split and Window ACs.',
    price: 1499,
    imageUrl: 'https://picsum.photos/400/300?random=201',
    tags: ['Drill-free options', 'Post-service Cleanup'],
    professional: { name: 'Rajesh Kumar', avatarUrl: 'https://picsum.photos/100/100?random=202', experience: '8+ years experience' },
    rating: 4.8,
    reviews: 789,
    duration: '2-4 hours',
    location: 'Chennai',
    verified: true,
  },
  {
    id: 202,
    categoryId: 'ac-repair',
    title: 'AC Gas Refill',
    description: 'Top-up and complete refill of AC refrigerant gas.',
    price: 2500,
    imageUrl: 'https://picsum.photos/400/300?random=203',
    tags: ['Leakage Check', '30-day Warranty'],
    professional: { name: 'Vikram Singh', avatarUrl: 'https://picsum.photos/100/100?random=13', experience: '6+ years experience' },
    rating: 4.7,
    reviews: 654,
    duration: '1-2 hours',
    location: 'Mumbai',
    availableNow: true,
  },

  // House Cleaning
  {
    id: 3,
    categoryId: 'house-cleaning',
    title: 'Deep House Cleaning',
    description: 'Complete deep cleaning of your home including bathrooms, kitchen, and all rooms',
    price: 2499,
    imageUrl: 'https://picsum.photos/400/300?random=1',
    tags: ['Deep Cleaning', 'Eco-friendly', 'Insurance Covered'],
    professional: { name: 'Rakesh Sharma', avatarUrl: 'https://picsum.photos/100/100?random=14', experience: '5+ years experience' },
    rating: 4.8,
    reviews: 1247,
    duration: '3-4 hours',
    location: 'Mumbai',
    availableNow: true,
  },
  {
    id: 301,
    categoryId: 'house-cleaning',
    title: 'Bathroom Deep Cleaning',
    description: 'Intensive cleaning of tiles, fixtures, and sanitation of your bathroom.',
    price: 799,
    imageUrl: 'https://picsum.photos/400/300?random=301',
    tags: ['Stain Removal', 'Disinfection'],
    professional: { name: 'Sunita Cleaning Co.', avatarUrl: 'https://picsum.photos/100/100?random=302', experience: 'Team of 5' },
    rating: 4.9,
    reviews: 987,
    duration: '1-2 hours',
    location: 'Delhi',
  },
  {
    id: 302,
    categoryId: 'house-cleaning',
    title: 'Kitchen Deep Cleaning',
    description: 'Complete degreasing and cleaning of kitchen including chimney & exhaust.',
    price: 999,
    imageUrl: 'https://picsum.photos/400/300?random=303',
    tags: ['Oil & Grease Removal', 'Eco-friendly Chemicals'],
    professional: { name: 'Rakesh Sharma', avatarUrl: 'https://picsum.photos/100/100?random=14', experience: '5+ years experience' },
    rating: 4.8,
    reviews: 876,
    duration: '2-3 hours',
    location: 'Mumbai',
    verified: true,
  },
  {
    id: 303,
    categoryId: 'house-cleaning',
    title: 'Sofa & Carpet Cleaning',
    description: 'Shampooing and deep cleaning of sofas, carpets, and upholstery.',
    price: 599,
    imageUrl: 'https://picsum.photos/400/300?random=304',
    tags: ['Fabric-safe', 'Quick Drying'],
    professional: { name: 'Clean & Clear', avatarUrl: 'https://picsum.photos/100/100?random=305', experience: 'Specialized Equipment' },
    rating: 4.7,
    reviews: 1102,
    duration: '1-2 hours',
    location: 'Bangalore',
    availableNow: true,
  },

  // Plumbing
  {
    id: 4,
    categoryId: 'plumbing',
    title: 'Plumbing Repair & Installation',
    description: 'Expert plumbing services for leaks, blockages, and new installations',
    price: 599,
    imageUrl: 'https://picsum.photos/400/300?random=2',
    tags: ['Emergency Service', '24/7 Available', 'Licensed'],
    professional: { name: 'Amit Kumar', avatarUrl: 'https://picsum.photos/100/100?random=15', experience: '8+ years experience' },
    rating: 4.7,
    reviews: 892,
    duration: '1-2 hours',
    location: 'Mumbai',
    availableNow: true,
    verified: true,
  },
  {
    id: 401,
    categoryId: 'plumbing',
    title: 'Blocked Drain & Sink Cleaning',
    description: 'Clear blockages in kitchen sinks, washbasins, and drain pipes.',
    price: 299,
    imageUrl: 'https://picsum.photos/400/300?random=401',
    tags: ['Fast Resolution', 'No Mess'],
    professional: { name: 'Raj Plumbers', avatarUrl: 'https://picsum.photos/100/100?random=402', experience: '15+ years experience' },
    rating: 4.8,
    reviews: 1500,
    duration: '1 hour',
    location: 'Pune',
    availableNow: true,
  },
  {
    id: 402,
    categoryId: 'plumbing',
    title: 'Tap & Faucet Repair',
    description: 'Repair and replacement of all types of taps, faucets, and mixers.',
    price: 249,
    imageUrl: 'https://picsum.photos/400/300?random=403',
    tags: ['All Brands', 'Leak-proof Guarantee'],
    professional: { name: 'Amit Kumar', avatarUrl: 'https://picsum.photos/100/100?random=15', experience: '8+ years experience' },
    rating: 4.7,
    reviews: 750,
    duration: '1 hour',
    location: 'Mumbai',
    verified: true,
  },
  {
    id: 403,
    categoryId: 'plumbing',
    title: 'Water Tank Cleaning',
    description: 'Multi-stage cleaning of overhead and underground water tanks.',
    price: 999,
    imageUrl: 'https://picsum.photos/400/300?random=404',
    tags: ['Mechanized Cleaning', 'Hygienic'],
    professional: { name: 'Aqua Clean', avatarUrl: 'https://picsum.photos/100/100?random=405', experience: 'Certified Team' },
    rating: 4.9,
    reviews: 1234,
    duration: '2-3 hours',
    location: 'Delhi',
  },
  
  // Appliance Repair
  {
    id: 501,
    categoryId: 'appliance-repair',
    title: 'Washing Machine Repair',
    description: 'Repair for all types of washing machines - top load, front load, semi-automatic.',
    price: 499,
    imageUrl: 'https://picsum.photos/400/300?random=501',
    tags: ['All Major Brands', '30-day Warranty'],
    professional: { name: 'Appliance Experts', avatarUrl: 'https://picsum.photos/100/100?random=502', experience: '10+ years experience' },
    rating: 4.8,
    reviews: 982,
    duration: '1-3 hours',
    location: 'Bangalore',
    verified: true,
  },
  {
    id: 502,
    categoryId: 'appliance-repair',
    title: 'Refrigerator Repair',
    description: 'Services for single door, double door, and side-by-side refrigerators.',
    price: 599,
    imageUrl: 'https://picsum.photos/400/300?random=503',
    tags: ['Gas Refill', 'Cooling Issues'],
    professional: { name: 'Cool Care Services', avatarUrl: 'https://picsum.photos/100/100?random=504', experience: '12+ years experience' },
    rating: 4.7,
    reviews: 1120,
    duration: '2-4 hours',
    location: 'Hyderabad',
    availableNow: true,
  },
  {
    id: 503,
    categoryId: 'appliance-repair',
    title: 'Microwave Repair',
    description: 'Repair for solo, grill, and convection microwaves. Not heating, sparking issues.',
    price: 449,
    imageUrl: 'https://picsum.photos/400/300?random=505',
    tags: ['Genuine Parts', 'On-site Repair'],
    professional: { name: 'Appliance Experts', avatarUrl: 'https://picsum.photos/100/100?random=502', experience: '10+ years experience' },
    rating: 4.8,
    reviews: 765,
    duration: '1-2 hours',
    location: 'Bangalore',
  },
  {
    id: 504,
    categoryId: 'appliance-repair',
    title: 'Water Purifier Service',
    description: 'RO/UV water purifier repair, installation, and filter change.',
    price: 399,
    imageUrl: 'https://picsum.photos/400/300?random=506',
    tags: ['All Brands', 'AMC Available'],
    professional: { name: 'Pure Water Solutions', avatarUrl: 'https://picsum.photos/100/100?random=507', experience: '8+ years experience' },
    rating: 4.9,
    reviews: 1843,
    duration: '1 hour',
    location: 'Delhi',
    verified: true,
  },

  // Painting
  {
    id: 601,
    categoryId: 'painting',
    title: 'Interior House Painting',
    description: 'Professional interior painting for a fresh new look for your home.',
    price: 4500,
    imageUrl: 'https://picsum.photos/400/300?random=601',
    tags: ['Color Consultation', 'On-time Completion'],
    professional: { name: 'Perfect Painters', avatarUrl: 'https://picsum.photos/100/100?random=602', experience: 'Team of 10' },
    rating: 4.9,
    reviews: 543,
    duration: '2-3 days',
    location: 'Mumbai',
    verified: true,
  },
  {
    id: 602,
    categoryId: 'painting',
    title: 'Exterior House Painting',
    description: 'Weather-proof and durable exterior painting services.',
    price: 8000,
    imageUrl: 'https://picsum.photos/400/300?random=603',
    tags: ['Crack Filling', 'Waterproof Coats'],
    professional: { name: 'Wallscapes', avatarUrl: 'https://picsum.photos/100/100?random=604', experience: '15+ years experience' },
    rating: 4.8,
    reviews: 432,
    duration: '4-5 days',
    location: 'Delhi',
  },
  {
    id: 603,
    categoryId: 'painting',
    title: 'Wood Polishing',
    description: 'Polishing services for doors, windows, and furniture.',
    price: 1200,
    imageUrl: 'https://picsum.photos/400/300?random=605',
    tags: ['Melamine', 'PU Polish'],
    professional: { name: 'Perfect Painters', avatarUrl: 'https://picsum.photos/100/100?random=602', experience: 'Team of 10' },
    rating: 4.7,
    reviews: 321,
    duration: '1-2 days',
    location: 'Mumbai',
  },

  // Carpentry
  {
    id: 701,
    categoryId: 'carpentry',
    title: 'Furniture Assembly',
    description: 'Hassle-free assembly of flat-pack furniture.',
    price: 699,
    imageUrl: 'https://picsum.photos/400/300?random=701',
    tags: ['All Brands', 'Quick & Tidy'],
    professional: { name: 'Kumar Carpenters', avatarUrl: 'https://picsum.photos/100/100?random=702', experience: '20+ years experience' },
    rating: 4.8,
    reviews: 890,
    duration: '2-3 hours',
    location: 'Bangalore',
    availableNow: true,
  },
  {
    id: 702,
    categoryId: 'carpentry',
    title: 'Door & Window Repair',
    description: 'Repair of hinges, locks, and frames for doors and windows.',
    price: 499,
    imageUrl: 'https://picsum.photos/400/300?random=703',
    tags: ['Lock Replacement', 'Sturdy Repairs'],
    professional: { name: 'SK Woodworks', avatarUrl: 'https://picsum.photos/100/100?random=704', experience: '12+ years experience' },
    rating: 4.7,
    reviews: 654,
    duration: '1-2 hours',
    location: 'Chennai',
    verified: true,
  },
  {
    id: 703,
    categoryId: 'carpentry',
    title: 'Custom Furniture Making',
    description: 'Bespoke furniture design and creation as per your needs.',
    price: 9999,
    imageUrl: 'https://picsum.photos/400/300?random=705',
    tags: ['Consultation', 'Quality Wood'],
    professional: { name: 'Kumar Carpenters', avatarUrl: 'https://picsum.photos/100/100?random=702', experience: '20+ years experience' },
    rating: 4.9,
    reviews: 210,
    duration: '5-10 days',
    location: 'Bangalore',
  },

  // Pest Control
  {
    id: 801,
    categoryId: 'pest-control',
    title: 'General Pest Control',
    description: 'Treatment for cockroaches, ants, and other common household pests.',
    price: 899,
    imageUrl: 'https://picsum.photos/400/300?random=801',
    tags: ['Eco-friendly', 'Odorless'],
    professional: { name: 'Pest Guard', avatarUrl: 'https://picsum.photos/100/100?random=802', experience: 'Govt. Licensed' },
    rating: 4.8,
    reviews: 1342,
    duration: '1-2 hours',
    location: 'Mumbai',
    verified: true,
  },
  {
    id: 802,
    categoryId: 'pest-control',
    title: 'Termite Control',
    description: 'Pre and post-construction anti-termite treatment.',
    price: 2500,
    imageUrl: 'https://picsum.photos/400/300?random=803',
    tags: ['5-Year Warranty', 'Drill-Fill-Seal'],
    professional: { name: 'NoPest', avatarUrl: 'https://picsum.photos/100/100?random=804', experience: '15+ years experience' },
    rating: 4.9,
    reviews: 998,
    duration: '3-4 hours',
    location: 'Delhi',
  },
  {
    id: 803,
    categoryId: 'pest-control',
    title: 'Bed Bugs Treatment',
    description: 'Effective treatment to eradicate bed bugs from your home.',
    price: 1500,
    imageUrl: 'https://picsum.photos/400/300?random=805',
    tags: ['Follow-up Visit', 'Chemical-safe'],
    professional: { name: 'Pest Guard', avatarUrl: 'https://picsum.photos/100/100?random=802', experience: 'Govt. Licensed' },
    rating: 4.7,
    reviews: 765,
    duration: '2-3 hours',
    location: 'Mumbai',
    availableNow: true,
  },
];
